$kind: http-example
request:
  url: "{{baseUrl}}/api/assets/:id/stream-upload"
  method: POST
  headers:
    - key: Idempotency-Key
      value: string
    - key: Content-Type
      value: application/json
    - key: Accept
      value: application/json
    - key: va_session
      value: <API Key>
      description: "Added as a part of security scheme: apikey"
  pathVariables:
    id: string
  body:
    type: json
    content: |-
      {
        "filename": "string",
        "contentType": "video/",
        "maxDurationSeconds": 3600
      }
response:
  statusCode: 503
  statusText: Service Unavailable
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "error": "string",
        "code": "string",
        "retryAfter": 4141,
        "quotaBytes": 2089,
        "uploadId": "string",
        "issues": [
          {
            "path": [
              "",
              ""
            ],
            "code": "string"
          },
          {
            "path": [
              "",
              ""
            ],
            "code": "string"
          }
        ]
      }
order: 2000
