$kind: http-example
request:
  url: "{{baseUrl}}/api/ops/readiness"
  method: GET
  headers:
    - key: Accept
      value: application/json
    - key: va_session
      value: <API Key>
      description: "Added as a part of security scheme: apikey"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "ready": true,
        "checkedAt": "1983-03-31T01:52:54.441Z",
        "checks": [
          {
            "id": "string",
            "ready": false,
            "action": "string"
          },
          {
            "id": "string",
            "ready": false,
            "action": "string"
          }
        ]
      }
order: 1000
