<?php
/**
 * Plugin Name: Stockvel Connector
 * Description: Search approved Stockvel imagery, import licensed preview derivatives, and retain rights provenance in WordPress.
 * Version: 0.1.0
 * Requires at least: 6.2
 * Requires PHP: 7.4
 * Author: Stockvel
 * License: GPL-2.0-or-later
 * Text Domain: veld-archive
 */

if (!defined('ABSPATH')) {
    exit;
}

final class Veld_Archive_WordPress_Connector {
    const VERSION = '0.1.0';
    const OPTION = 'veld_archive_connector';
    const CRON = 'veld_archive_connector_sync_notices';

    public static function boot() {
        $instance = new self();
        add_action('admin_menu', array($instance, 'admin_menu'));
        add_action('admin_post_veld_archive_pair', array($instance, 'pair'));
        add_action('admin_post_veld_archive_disconnect', array($instance, 'disconnect'));
        add_action('admin_post_veld_archive_import', array($instance, 'import_asset'));
        add_action('admin_post_veld_archive_hosted', array($instance, 'hosted_asset'));
        add_action(self::CRON, array($instance, 'sync_notices'));
        add_action('admin_notices', array($instance, 'admin_notices'));
        add_shortcode('veld_archive_image', array($instance, 'shortcode'));
    }

    public static function activate() {
        if (!wp_next_scheduled(self::CRON)) {
            wp_schedule_event(time() + HOUR_IN_SECONDS, 'twicedaily', self::CRON);
        }
    }

    public static function deactivate() {
        wp_clear_scheduled_hook(self::CRON);
    }

    public function admin_menu() {
        add_menu_page(
            __('Stockvel', 'veld-archive'),
            __('Stockvel', 'veld-archive'),
            'upload_files',
            'veld-archive',
            array($this, 'screen'),
            'dashicons-format-image',
            58
        );
    }

    public function screen() {
        if (!current_user_can('upload_files')) {
            wp_die(esc_html__('You do not have permission to use the Stockvel connector.', 'veld-archive'));
        }
        $settings = $this->settings();
        $query = isset($_GET['veld_q']) ? sanitize_text_field(wp_unslash($_GET['veld_q'])) : '';
        $results = array();
        $error = '';
        if ($query !== '' && $this->connected()) {
            $response = $this->api_request('GET', '/api/integrations/wordpress/v1/assets?' . http_build_query(array('q' => $query, 'kind' => 'image', 'limit' => 20)));
            if (is_wp_error($response)) {
                $error = $response->get_error_message();
            } else {
                $results = isset($response['results']) && is_array($response['results']) ? $response['results'] : array();
            }
        }
        ?>
        <div class="wrap">
            <h1><?php echo esc_html__('Stockvel', 'veld-archive'); ?></h1>
            <?php $this->render_messages(); ?>
            <?php if ($error) : ?><div class="notice notice-error"><p><?php echo esc_html($error); ?></p></div><?php endif; ?>
            <?php if (!$this->connected()) : ?>
                <div class="notice notice-info"><p><?php echo esc_html__('Connect this site with a ten-minute pairing code generated by an authorised Stockvel organisation user.', 'veld-archive'); ?></p></div>
            <?php endif; ?>
            <?php if (current_user_can('manage_options')) : ?>
                <h2><?php echo esc_html__('Connection', 'veld-archive'); ?></h2>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
                    <input type="hidden" name="action" value="veld_archive_pair" />
                    <?php wp_nonce_field('veld_archive_pair'); ?>
                    <table class="form-table" role="presentation">
                        <tr><th scope="row"><label for="veld-api-base-url"><?php echo esc_html__('Stockvel API base URL', 'veld-archive'); ?></label></th><td><input class="regular-text" id="veld-api-base-url" name="api_base_url" type="url" required value="<?php echo esc_attr($settings['api_base_url']); ?>" placeholder="https://veld-archive.pages.dev" /><p class="description"><?php echo esc_html__('Use the URL returned by the pairing screen, without credentials.', 'veld-archive'); ?></p></td></tr>
                        <tr><th scope="row"><label for="veld-pairing-code"><?php echo esc_html__('Pairing code', 'veld-archive'); ?></label></th><td><input class="regular-text" id="veld-pairing-code" name="pairing_code" type="password" autocomplete="off" required /><p class="description"><?php echo esc_html__('The code is used once and is not stored by WordPress after exchange.', 'veld-archive'); ?></p></td></tr>
                    </table>
                    <?php submit_button($this->connected() ? __('Replace connection', 'veld-archive') : __('Connect site', 'veld-archive')); ?>
                </form>
                <?php if ($this->connected()) : ?>
                    <p><strong><?php echo esc_html__('Connected site:', 'veld-archive'); ?></strong> <?php echo esc_html($settings['site_url']); ?> <span class="description">(<?php echo esc_html($settings['connection_id']); ?>)</span></p>
                    <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
                        <input type="hidden" name="action" value="veld_archive_disconnect" />
                        <?php wp_nonce_field('veld_archive_disconnect'); ?>
                        <?php submit_button(__('Disconnect this site', 'veld-archive'), 'delete', 'submit', false); ?>
                    </form>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->connected()) : ?>
                <hr />
                <h2><?php echo esc_html__('Find approved imagery', 'veld-archive'); ?></h2>
                <form method="get">
                    <input type="hidden" name="page" value="veld-archive" />
                    <label for="veld-search-query" class="screen-reader-text"><?php echo esc_html__('Search Stockvel', 'veld-archive'); ?></label>
                    <input id="veld-search-query" name="veld_q" type="search" class="regular-text" value="<?php echo esc_attr($query); ?>" placeholder="Cape Town, mountain, market..." />
                    <?php submit_button(__('Search', 'veld-archive'), 'secondary', '', false); ?>
                </form>
                <?php if ($query !== '') : ?>
                    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px;margin-top:20px;max-width:1100px">
                    <?php foreach ($results as $asset) : $this->render_asset_card($asset); endforeach; ?>
                    </div>
                    <?php if (!$results) : ?><p><?php echo esc_html__('No approved preview-backed images matched this search.', 'veld-archive'); ?></p><?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <?php
    }

    private function render_asset_card($asset) {
        $asset_id = isset($asset['id']) ? sanitize_text_field($asset['id']) : '';
        $licence = isset($asset['activeLicence']) && is_array($asset['activeLicence']) ? $asset['activeLicence'] : array();
        $licence_id = isset($licence['id']) ? sanitize_text_field($licence['id']) : '';
        $preview = isset($asset['previewUrl']) ? esc_url($asset['previewUrl']) : '';
        $title = isset($asset['title']) ? $asset['title'] : '';
        ?>
        <article style="border:1px solid #dcdcde;background:#fff;padding:12px">
            <?php if ($preview) : ?><img src="<?php echo $preview; ?>" alt="" loading="lazy" style="display:block;width:100%;height:170px;object-fit:cover;margin-bottom:10px" /><?php endif; ?>
            <h3 style="margin:0 0 6px"><?php echo esc_html($title); ?></h3>
            <p style="margin:0 0 8px;color:#50575e"><?php echo esc_html(implode(', ', array_filter(array(isset($asset['city']) ? $asset['city'] : '', isset($asset['province']) ? $asset['province'] : '')))); ?></p>
            <p style="margin:0 0 8px"><strong><?php echo esc_html__('Rights:', 'veld-archive'); ?></strong> <?php echo esc_html(isset($asset['rightsStatus']) ? $asset['rightsStatus'] : 'unknown'); ?><br /><strong><?php echo esc_html__('Licence:', 'veld-archive'); ?></strong> <?php echo esc_html($licence_id ? (isset($licence['type']) ? $licence['type'] : 'active') : __('Required in Stockvel', 'veld-archive')); ?></p>
            <?php if ($licence_id) : ?>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" style="display:inline-block;margin-right:6px">
                    <input type="hidden" name="action" value="veld_archive_import" /><input type="hidden" name="asset_id" value="<?php echo esc_attr($asset_id); ?>" /><input type="hidden" name="licence_id" value="<?php echo esc_attr($licence_id); ?>" /><input type="hidden" name="variant" value="preview" /><?php wp_nonce_field('veld_archive_import_' . $asset_id); ?><button class="button button-primary" type="submit"><?php echo esc_html__('Import to Media Library', 'veld-archive'); ?></button>
                </form>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" style="display:inline-block">
                    <input type="hidden" name="action" value="veld_archive_hosted" /><input type="hidden" name="asset_id" value="<?php echo esc_attr($asset_id); ?>" /><input type="hidden" name="licence_id" value="<?php echo esc_attr($licence_id); ?>" /><input type="hidden" name="variant" value="card" /><?php wp_nonce_field('veld_archive_hosted_' . $asset_id); ?><button class="button" type="submit"><?php echo esc_html__('Get hosted shortcode', 'veld-archive'); ?></button>
                </form>
            <?php else : ?><p class="description"><?php echo esc_html__('Purchase or activate an eligible licence in Stockvel before importing this image.', 'veld-archive'); ?></p><?php endif; ?>
        </article>
        <?php
    }

    public function pair() {
        if (!current_user_can('manage_options')) wp_die(esc_html__('Administrator access required.', 'veld-archive'));
        check_admin_referer('veld_archive_pair');
        $base = $this->safe_api_base(isset($_POST['api_base_url']) ? wp_unslash($_POST['api_base_url']) : '');
        $code = isset($_POST['pairing_code']) ? trim(sanitize_text_field(wp_unslash($_POST['pairing_code']))) : '';
        if (!$base || !$code) $this->redirect('error', __('Enter a valid API URL and pairing code.', 'veld-archive'));
        $this->save_settings(array('api_base_url' => $base));
        $response = $this->api_request('POST', '/api/integrations/wordpress/pairing/exchange', array('pairingCode' => $code, 'siteUrl' => untrailingslashit(home_url('/')), 'siteName' => get_bloginfo('name'), 'pluginVersion' => self::VERSION), false, true);
        if (is_wp_error($response)) $this->redirect('error', $response->get_error_message());
        if (empty($response['accessToken']) || empty($response['connectionId'])) $this->redirect('error', __('The Stockvel API returned an incomplete connection response.', 'veld-archive'));
        $this->save_settings(array('api_base_url' => $base, 'connection_id' => sanitize_text_field($response['connectionId']), 'site_url' => untrailingslashit(home_url('/')), 'site_name' => get_bloginfo('name'), 'token' => $this->encrypt(sanitize_text_field($response['accessToken']))));
        $this->redirect('success', __('WordPress is connected to Stockvel.', 'veld-archive'));
    }

    public function disconnect() {
        if (!current_user_can('manage_options')) wp_die(esc_html__('Administrator access required.', 'veld-archive'));
        check_admin_referer('veld_archive_disconnect');
        if ($this->connected()) $this->api_request('POST', '/api/integrations/wordpress/v1/disconnect', array(), true);
        $settings = $this->settings();
        $this->save_settings(array('api_base_url' => $settings['api_base_url'], 'connection_id' => '', 'site_url' => '', 'site_name' => '', 'token' => ''));
        $this->redirect('success', __('The WordPress connection was removed from this site.', 'veld-archive'));
    }

    public function import_asset() {
        if (!current_user_can('upload_files')) wp_die(esc_html__('Upload permission required.', 'veld-archive'));
        $asset_id = isset($_POST['asset_id']) ? sanitize_text_field(wp_unslash($_POST['asset_id'])) : '';
        check_admin_referer('veld_archive_import_' . $asset_id);
        $licence_id = isset($_POST['licence_id']) ? sanitize_text_field(wp_unslash($_POST['licence_id'])) : '';
        $variant = isset($_POST['variant']) ? sanitize_key($_POST['variant']) : 'preview';
        $response = $this->api_request('GET', '/api/integrations/wordpress/v1/assets/' . rawurlencode($asset_id) . '/media?' . http_build_query(array('licenceId' => $licence_id, 'variant' => $variant)), true);
        if (is_wp_error($response)) $this->redirect('error', $response->get_error_message());
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';
        $filename = sanitize_file_name($asset_id . '-' . $variant . '.jpg');
        $temporary = wp_tempnam($filename);
        if (!$temporary || false === file_put_contents($temporary, $response['body'])) $this->redirect('error', __('The licensed preview could not be written to temporary storage.', 'veld-archive'));
        $attachment_id = media_handle_sideload(array('name' => $filename, 'tmp_name' => $temporary, 'type' => isset($response['content_type']) ? $response['content_type'] : 'image/jpeg', 'size' => strlen($response['body'])), 0);
        if (is_wp_error($attachment_id)) { @unlink($temporary); $this->redirect('error', $attachment_id->get_error_message()); }
        update_post_meta($attachment_id, '_veld_archive_asset_id', $asset_id);
        update_post_meta($attachment_id, '_veld_archive_licence_id', $licence_id);
        update_post_meta($attachment_id, '_veld_archive_variant', $variant);
        update_post_meta($attachment_id, '_veld_archive_imported_at', current_time('mysql', true));
        $this->api_request('POST', '/api/integrations/wordpress/v1/usages', array('assetId' => $asset_id, 'licenceId' => $licence_id, 'mode' => 'imported', 'variant' => $variant, 'wordpressAttachmentId' => (string) $attachment_id), true);
        $this->redirect('success', sprintf(__('Image imported as Media Library attachment #%d.', 'veld-archive'), $attachment_id));
    }

    public function hosted_asset() {
        if (!current_user_can('upload_files')) wp_die(esc_html__('Upload permission required.', 'veld-archive'));
        $asset_id = isset($_POST['asset_id']) ? sanitize_text_field(wp_unslash($_POST['asset_id'])) : '';
        check_admin_referer('veld_archive_hosted_' . $asset_id);
        $licence_id = isset($_POST['licence_id']) ? sanitize_text_field(wp_unslash($_POST['licence_id'])) : '';
        $variant = isset($_POST['variant']) ? sanitize_key($_POST['variant']) : 'card';
        $response = $this->api_request('POST', '/api/integrations/wordpress/v1/usages', array('assetId' => $asset_id, 'licenceId' => $licence_id, 'mode' => 'hosted', 'variant' => $variant), true);
        if (is_wp_error($response)) $this->redirect('error', $response->get_error_message());
        $shortcode = sprintf('[veld_archive_image asset_id="%s" licence_id="%s" variant="%s"]', esc_attr($asset_id), esc_attr($licence_id), esc_attr($variant));
        $this->redirect('shortcode', $shortcode);
    }

    public function shortcode($attributes) {
        $attributes = shortcode_atts(array('asset_id' => '', 'licence_id' => '', 'variant' => 'card', 'alt' => ''), $attributes, 'veld_archive_image');
        $asset_id = sanitize_text_field($attributes['asset_id']);
        $licence_id = sanitize_text_field($attributes['licence_id']);
        $variant = in_array($attributes['variant'], array('thumb', 'card', 'preview'), true) ? $attributes['variant'] : 'card';
        if (!$asset_id || !$licence_id || !$this->connected()) return '';
        $base = $this->settings()['api_base_url'];
        $url = trailingslashit($base) . 'api/assets/' . rawurlencode($asset_id) . '/image/' . rawurlencode($variant);
        return '<img src="' . esc_url($url) . '" alt="' . esc_attr($attributes['alt']) . '" data-veld-archive-asset="' . esc_attr($asset_id) . '" data-veld-archive-licence="' . esc_attr($licence_id) . '" loading="lazy" />';
    }

    public function sync_notices() {
        if (!$this->connected()) return;
        $response = $this->api_request('GET', '/api/integrations/wordpress/v1/notices');
        if (!is_wp_error($response) && isset($response['results']) && is_array($response['results'])) {
            $settings = $this->settings();
            $settings['notices'] = $response['results'];
            $settings['notices_checked_at'] = current_time('mysql', true);
            update_option(self::OPTION, $settings, false);
        }
    }

    public function admin_notices() {
        if (!current_user_can('manage_options')) return;
        $settings = $this->settings();
        foreach (array_slice($settings['notices'], 0, 5) as $notice) {
            $class = isset($notice['severity']) && $notice['severity'] === 'blocked' ? 'notice-error' : 'notice-warning';
            printf('<div class="notice %1$s"><p>%2$s: %3$s (licence %4$s)</p></div>', esc_attr($class), esc_html__('Stockvel rights notice', 'veld-archive'), esc_html(isset($notice['title']) ? $notice['title'] : ''), esc_html(isset($notice['licenceId']) ? $notice['licenceId'] : 'unknown'));
        }
    }

    private function render_messages() {
        if (isset($_GET['veld_message'])) {
            $class = isset($_GET['veld_status']) && $_GET['veld_status'] === 'error' ? 'notice-error' : 'notice-success';
            echo '<div class="notice ' . esc_attr($class) . '"><p>' . esc_html(wp_unslash($_GET['veld_message'])) . '</p></div>';
        }
        if (isset($_GET['veld_shortcode'])) {
            echo '<div class="notice notice-success"><p>' . esc_html__('Copy this shortcode into a post or block:', 'veld-archive') . '</p><textarea readonly style="width:100%;max-width:680px" rows="2">' . esc_textarea(wp_unslash($_GET['veld_shortcode'])) . '</textarea></div>';
        }
    }

    private function redirect($status, $message) {
        $args = array('page' => 'veld-archive');
        if ($status === 'shortcode') $args['veld_shortcode'] = $message; else { $args['veld_status'] = $status === 'error' ? 'error' : 'success'; $args['veld_message'] = $message; }
        wp_safe_redirect(add_query_arg($args, admin_url('admin.php')));
        exit;
    }

    private function settings() {
        $settings = get_option(self::OPTION, array());
        return wp_parse_args(is_array($settings) ? $settings : array(), array('api_base_url' => '', 'connection_id' => '', 'site_url' => '', 'site_name' => '', 'token' => '', 'notices' => array(), 'notices_checked_at' => ''));
    }

    private function save_settings($next) {
        update_option(self::OPTION, array_merge($this->settings(), $next), false);
    }

    private function connected() {
        $settings = $this->settings();
        return !empty($settings['connection_id']) && !empty($settings['token']) && !empty($settings['api_base_url']);
    }

    private function safe_api_base($value) {
        $value = untrailingslashit(esc_url_raw(trim($value)));
        if (!$value) return '';
        $parts = wp_parse_url($value);
        if (!$parts || empty($parts['host']) || (!empty($parts['scheme']) && $parts['scheme'] !== 'https' && !in_array($parts['host'], array('localhost', '127.0.0.1'), true))) return '';
        return $value;
    }

    private function api_request($method, $path, $body = null, $authenticated = true, $pairing = false) {
        $settings = $this->settings();
        $base = $this->safe_api_base($settings['api_base_url']);
        if (!$base) return new WP_Error('veld_archive_api_url', __('The Stockvel API base URL is not configured.', 'veld-archive'));
        $headers = array('Accept' => 'application/json', 'User-Agent' => 'StockvelWordPress/' . self::VERSION);
        if ($authenticated) {
            $token = $this->decrypt($settings['token']);
            if (!$token) return new WP_Error('veld_archive_token', __('The encrypted Stockvel connector token is unavailable. Reconnect this site.', 'veld-archive'));
            $headers['Authorization'] = 'Bearer ' . $token;
        }
        $args = array('method' => $method, 'timeout' => 25, 'headers' => $headers, 'reject_unsafe_urls' => false);
        if ($body !== null && $method !== 'GET') { $headers['Content-Type'] = 'application/json'; $args['headers'] = $headers; $args['body'] = wp_json_encode($body); }
        $response = wp_safe_remote_request($base . '/' . ltrim($path, '/'), $args);
        if (is_wp_error($response)) return $response;
        $status = wp_remote_retrieve_response_code($response);
        $raw = wp_remote_retrieve_body($response);
        $content_type = wp_remote_retrieve_header($response, 'content-type');
        if ($status >= 400) {
            $decoded = json_decode($raw, true);
            return new WP_Error('veld_archive_api_error', is_array($decoded) && !empty($decoded['error']) ? sanitize_text_field($decoded['error']) : sprintf(__('Stockvel API returned HTTP %d.', 'veld-archive'), $status), array('status' => $status));
        }
        if (strpos((string) $content_type, 'application/json') === false) return array('body' => $raw, 'content_type' => $content_type, 'status' => $status);
        $decoded = json_decode($raw, true);
        return is_array($decoded) ? $decoded : array();
    }

    private function encrypt($plaintext) {
        if (!function_exists('openssl_encrypt')) return '';
        $key = hash('sha256', wp_salt('auth'), true);
        $iv = openssl_random_pseudo_bytes(12);
        $tag = '';
        $ciphertext = openssl_encrypt($plaintext, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag);
        return $ciphertext === false ? '' : base64_encode($iv . $tag . $ciphertext);
    }

    private function decrypt($encoded) {
        if (!$encoded || !function_exists('openssl_decrypt')) return '';
        $payload = base64_decode($encoded, true);
        if ($payload === false || strlen($payload) < 28) return '';
        $key = hash('sha256', wp_salt('auth'), true);
        $iv = substr($payload, 0, 12); $tag = substr($payload, 12, 16); $ciphertext = substr($payload, 28);
        $plaintext = openssl_decrypt($ciphertext, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag);
        return $plaintext === false ? '' : $plaintext;
    }
}

register_activation_hook(__FILE__, array('Veld_Archive_WordPress_Connector', 'activate'));
register_deactivation_hook(__FILE__, array('Veld_Archive_WordPress_Connector', 'deactivate'));
Veld_Archive_WordPress_Connector::boot();
