import { useEffect, useState } from "react";
import type { CommunityOverview, TakedownReason } from "./shared";

const emptyCommunity: CommunityOverview = { forums: [], threads: [], showcases: [], collections: [] };

const reasons: Record<TakedownReason, string> = { copyright: "Copyright ownership", consent: "Consent or release", cultural_harm: "Cultural harm or misrepresentation", privacy: "Privacy or safety", metadata: "Incorrect metadata", other: "Something else" };

export function CommunityWorkspace({ api, onNotice }: { api: (path: string, init?: RequestInit) => Promise<Response>; onNotice: (notice: string) => void }) {
  const [data, setData] = useState(emptyCommunity);
  const [caseOpen, setCaseOpen] = useState(false);
  const [caseId, setCaseId] = useState("");
  const [reason, setReason] = useState<TakedownReason>("copyright");
  const [summary, setSummary] = useState("");
  const [mediation, setMediation] = useState(true);
  const [assetId, setAssetId] = useState("");

  useEffect(() => { api("/api/community/overview").then(async (response) => { if (response.ok) setData(await response.json() as CommunityOverview); }).catch(() => undefined); }, [api]);

  async function lodge(event: React.FormEvent) {
    event.preventDefault();
    try {
      const response = await api("/api/rights/takedown", { method: "POST", body: JSON.stringify({ assetId, reason, summary, mediationRequested: mediation }) });
      if (!response.ok) throw new Error("The case was not accepted by the server.");
      const record = await response.json() as { id: string };
      setCaseId(record.id); onNotice(`Case ${record.id} lodged. Response target: 5 working days.`);
    } catch { onNotice("The case was not lodged. Sign in, check the asset ID, and try again."); }
  }

  return <main className="community-page"><section className="workspace-intro"><span className="section-kicker">COMMUNITY & COLLECTIONS</span><h1>Make the archive<br /><em>with us.</em></h1><p>Contributor forums, editorial showcases, and region-led collections keep the people and places behind the work visible.</p></section>
    <section className="community-section"><div className="section-heading"><div><span className="section-kicker">CONTRIBUTOR FORUMS</span><h2>Knowledge is <em>shared.</em></h2></div><p className="section-intro">Moderated spaces for practical exchange, rights questions, and paid opportunities.</p></div><div className="community-layout"><div className="forum-list">{data.forums.map((forum) => <article className="forum-card" key={forum.id}><div className="forum-icon" aria-hidden="true">✳</div><div><h3>{forum.name}</h3><p>{forum.description}</p><span>{forum.topicCount} topics · {forum.postCount} posts</span></div></article>)}</div><div className="thread-panel"><div className="panel-heading"><span className="section-kicker">DISCUSSIONS TO START WITH</span><button type="button" className="text-button" onClick={() => onNotice("Sign in to start a moderated community discussion.")}>Start a discussion <span aria-hidden="true">↗</span></button></div>{data.threads.map((thread) => <button type="button" className="thread-row" key={thread.id} onClick={() => onNotice(`Opening “${thread.title}” — community discussion is ready for sign-in.`)}><span className="thread-marker" aria-hidden="true">{thread.featured ? "★" : "·"}</span><span><strong>{thread.title}</strong><small>{thread.excerpt}</small><small>{thread.author} · {thread.replies} replies · {thread.lastActivity}</small></span><span aria-hidden="true">↗</span></button>)}</div></div></section>
    <section className="showcase-section"><div className="section-heading"><div><span className="section-kicker">EDITORIAL & COMMUNITY EDITS</span><h2>Stories with a <em>point of view.</em></h2></div><p className="section-intro">Curated showcases give context a front seat. Featured collections make regions easier to discover.</p></div><div className="showcase-grid">{data.showcases.map((showcase, index) => <button type="button" className={`showcase-card showcase-${index + 1}`} key={showcase.id} onClick={() => onNotice(`${showcase.title} — ${showcase.theme} showcase by ${showcase.curator}.`)}><span className="collection-art" aria-hidden="true"><span>{index === 0 ? "after / rain" : "long / way"}</span></span><span className="showcase-copy"><small>{showcase.theme}</small><strong>{showcase.title}</strong><span>{showcase.description}</span><em>Curated by {showcase.curator} ↗</em></span></button>)}</div><div className="collection-heading"><span className="section-kicker">FEATURED SOUTH AFRICAN COLLECTIONS</span><span>Updated monthly with contributor review</span></div><div className="collection-grid">{data.collections.map((collection) => <button type="button" className="collection-card" key={collection.id} onClick={() => onNotice(`${collection.title}: ${collection.assetCount} assets from ${collection.contributorCount} contributors.`)}><span className="collection-label">{collection.featuredLabel}</span><h3>{collection.title}</h3><p>{collection.description}</p><span className="collection-meta">{collection.location} <span aria-hidden="true">·</span> {collection.assetCount} assets <span aria-hidden="true">·</span> {collection.contributorCount} contributors</span></button>)}</div></section>
    <section className="resolution-section"><div><span className="section-kicker">RIGHTS & CARE</span><h2>Resolve it with<br /><em>context.</em></h2></div><div><p>Each concern gets a case ID, evidence record, response window, and optional independent mediation room. Nothing disappears into an inbox.</p><div className="resolution-steps"><div><strong>01</strong><span>Lodge & preserve</span><small>Evidence and visibility are recorded.</small></div><div><strong>02</strong><span>Review together</span><small>Contributor response within 5 working days.</small></div><div><strong>03</strong><span>Mediate or appeal</span><small>A neutral facilitator can join the case.</small></div></div><button type="button" className="dark-button" onClick={() => setCaseOpen((open) => !open)}>{caseOpen ? "Close case form" : "Open a resolution case"} <span aria-hidden="true">↗</span></button></div></section>
    {caseOpen && <section className="rights-modal rights-inline" aria-labelledby="rights-form-title">{caseId ? <div className="case-confirmation"><span className="case-check" aria-hidden="true">✓</span><span className="section-kicker">CASE LODGED</span><h2 id="rights-form-title">Your concern has a<br /><em>clear next step.</em></h2><p>Keep this case ID for follow-up. Mediation requested: {mediation ? "yes" : "no"}.</p><div className="case-id"><span>Case ID</span><strong>{caseId}</strong></div><button type="button" className="dark-button" onClick={() => { setCaseId(""); setCaseOpen(false); }}>Done</button></div> : <form onSubmit={lodge}><span className="section-kicker">STRUCTURED TAKEDOWN / DISPUTE</span><h2 id="rights-form-title">Open a resolution<br /><em>case.</em></h2><p className="dialog-intro">Share the context and requested remedy. The archive preserves the record and notifies the relevant contributor.</p><div className="form-grid"><div className="field"><label htmlFor="rights-asset">Asset ID</label><input id="rights-asset" required value={assetId} onChange={(event) => setAssetId(event.target.value)} placeholder="Paste the asset ID" /></div><div className="field"><label htmlFor="rights-reason">Reason</label><select id="rights-reason" value={reason} onChange={(event) => setReason(event.target.value as TakedownReason)}>{Object.entries(reasons).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="field field-wide"><label htmlFor="rights-summary">What should the review team know?</label><textarea id="rights-summary" required minLength={20} maxLength={2000} value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Share the context, evidence, or requested remedy…" /><small>{summary.length}/2000 characters</small></div><label className="mediation-toggle"><input type="checkbox" checked={mediation} onChange={(event) => setMediation(event.target.checked)} /><span><b>Invite mediation</b><small>Request a neutral facilitator and private message room if the case needs a conversation.</small></span></label></div><div className="dialog-footer"><span>Response target: 5 working days</span><button type="submit" className="dark-button">Lodge case <span aria-hidden="true">↗</span></button></div></form>}</section>}</main>;
}
